on:
  push:
    paths: 
      - 'project2/**'

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: project2
          path: project2
      - name: verify folder
        run: ls -l
      - name: install netlify
        run: npm i -g netlify-cli
      - name: deploy to netlify 2
        run: netlify deploy --prod --dir=project2 --site ${{ secrets.NETLIFY_SITE_ID2 }} --auth ${{ secrets.NETLIFY_API_TOKEN }}