on:
  push:
    branches: master

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: upload artifact
        uses: actions/upload-artifact@v4
      - name: verify folder
        run: ls -l