name: Push to windows server

on:
  push:
    paths: 
      - 'project3/**'


jobs:
  deployment:
    name: Deploy to windows
    runs-on: ubuntu-latest
    steps:
      - name: step1 Checkout
        uses: actions/checkout@v4

      - name: echo
        run: ls -l ./project3

      - name: copy to windows server
        run: sshpass -p StrictHostKeyChecking=no "${{secrets.REMOTE_PASS}}" scp project3/hasanym.html ${{ secrets.USERNAME }}@${{ secrets.IP }}:C:/inetpub/wwwroot/